### ISSUE TITLE
ADE&ADE_World

### ISSUE THREAD

**Issue by Jhfyut** [luigifilippochiara/Goal-SAR#10]
Hello, what is the meaning of ADE and ADE_World, what is the difference and which indicator is used in the paper, thank you

**Comment by luigifilippochiara** [comment]
Hi @Jhfyut , usually ADE is measured in pixels (image coordinates), why ADE_World is the same but in meters (world coordinates). Which one to use depends on the dataset (pixels for SDD, meters for inD and eth5). Hope this answers your question
