### ISSUE TITLE
How to produce {scene_name}_mask and pred_mask?

### ISSUE THREAD

**Issue by knakjbdhjahh** [luigifilippochiara/Goal-SAR#5]
Hi, it is really nice research work! but may you help me to explain the procedure to create and save {scene_name}_mask.png and pred_mask.png on the pre-processing process? Thank you in advance!

**Comment by luigifilippochiara** [comment]
Hi @liaastute and thank you! {scene_name}_mask.png and pred_mask.png are the GT and predicted semantic segmentation for each scene. The ground truth were manually annotated, while the prediction are obtained from a pretrained model that you can find at this project [url](https://github.com/HarshayuGirase/Human-Path-Prediction/tree/master/ynet)

**Comment by knakjbdhjahh** [comment]
Sorry, I still don't understand how to manually annotated the ground truth of {scene_name}_mask.png. If possible, may you share related references to do this step? Because when I search on google, there is too much information regarding this step. Thank you so much for helping 🙏
