### ISSUE TITLE
env error

### ISSUE THREAD

**Issue by guilunmeibeautiful** [luigifilippochiara/Goal-SAR#6]
Great job. I want to run your code, but I encountered an error when installing the environment under Windows. Can I run this code under Windows?
![20230206234216](https://user-images.githubusercontent.com/66264814/217016840-5f9fff76-bba4-4ea3-b24d-c8b49f8a415e.png)

**Comment by luigifilippochiara** [comment]
Hi @guilunmeibeautiful and thank you. No, you can't run that code in Windows. The environment you are trying to install has been tested only for linux. If you want to run the code on Windows you can manually install all the dependencies listed in [Goal-SAR/envs/GoalSARany.yml](https://github.com/luigifilippochiara/Goal-SAR/tree/main/envs/GoalSARany.yml) and it should work. In any case, it is recommended to run the project in linux to obtain the same results. Hope this helps

**Comment by guilunmeibeautiful** [comment]
Thank you very much. It's very helpful. 👍 :D@luigifilippochiara

**Comment by luigifilippochiara** [comment]
You're welcome @guilunmeibeautiful ! =)
