### ISSUE TITLE
Input images for the eth5 dataset

### ISSUE THREAD

**Issue by guilunmeibeautiful** [luigifilippochiara/Goal-SAR#7]
Hello, great job. I have been researching your work recently. Your model input contains scene image information and historical trajectory, but the ETH/UCY dataset does not have image information. So how did you handle this? I hope to receive your reply. Thank you very much.

**Comment by luigifilippochiara** [comment]
Hi @guilunmeibeautiful, and thank you. ETH/UCY do contain RGB images, which have been manually segmented into 6 semantic classes. Hope this helps.

**Comment by guilunmeibeautiful** [comment]
Thank you very much.  :D

**Comment by luigifilippochiara** [comment]
You're welcome!
